"""removed username

Revision ID: afe7eb6ba9c6
Revises: 1874ef8219e9
Create Date: 2022-11-30 13:15:38.397255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afe7eb6ba9c6'
down_revision = '1874ef8219e9'
branch_labels = None
depends_on = None


def upgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
