"""create stuff

Revision ID: ee20d33a2887
Revises: 2f44081de2c0
Create Date: 2022-11-23 21:26:57.996214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee20d33a2887'
down_revision = '2f44081de2c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spotimages', sa.Column('order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spotimages', 'order')
    # ### end Alembic commands ###
